# Generated by Django 3.2.16 on 2022-11-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('data_Nasc', models.DateField(auto_now=True, verbose_name='Data de Nascimento')),
                ('email', models.EmailField(max_length=300, verbose_name='Email')),
                ('senha', models.CharField(max_length=30, verbose_name='Senha de Usuario')),
            ],
        ),
    ]
