# Generated by Django 3.2.16 on 2022-11-17 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_Projeto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariomodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuariomodel',
            name='data_Nasc',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
    ]
